# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'HeartbeatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeartbeatApp
  pod 'iOSDropDown'
  pod 'Alamofire', '~> 4.7.1'
end
